# Generated by Django 5.2.8 on 2025-11-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('target_language', models.CharField(choices=[('Luo', 'Luo'), ('Kikuyu', 'Kikuyu'), ('Luhya', 'Luhya'), ('Kisii', 'Kisii')], max_length=20)),
                ('translated_file', models.FileField(blank=True, null=True, upload_to='translated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
        ),
    ]
